server:
  port: 18081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://38.76.188.242:5433/dating_dev_hanlian?stringtype=unspecified
    username: jianjian_test
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-init-sql: SET TIME ZONE 'UTC'
  cloud:
    nacos:
      discovery:
        server-addr: 38.76.188.242:8848
        namespace: dev-hanlian
        username: nacos
        password: ${NACOS_PASSWORD}
  data:
    redis:
      host: 38.76.188.242
      port: 6380
      password: ${REDIS_PASSWORD}
      database: 1
      timeout: 3s

management:
  endpoints:
    web:
      exposure:
        include: health

grpc:
  server:
    port: 19081
