server:
  port: 18081

spring:
  application:
    name: user-service
  config:
    import: optional:nacos:user-service.yaml
  cloud:
    nacos:
      discovery:
        server-addr: 38.76.188.242:8848
        namespace: dev-hanlian
        username: nacos
        password: ${NACOS_PASSWORD}
      config:
        server-addr: 38.76.188.242:8848
        namespace: dev-hanlian
        username: nacos
        password: ${NACOS_PASSWORD}
        file-extension: yaml

management:
  endpoints:
    web:
      exposure:
        include: health

grpc:
  server:
    port: 19081

aurora:
  id:
    datacenter-id: 1
    worker-id: 1
