server:
  port: 8080

spring:
  application:
    name: mobile-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 38.76.188.242:8848
        namespace: dev-hanlian
        username: nacos
        password: ${NACOS_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: health

user-service:
  grpc:
    host: 127.0.0.1
    port: 19081

match-service:
  grpc:
    host: 127.0.0.1
    port: 19083

im-service:
  grpc:
    host: 127.0.0.1
    port: 19082

post-service:
  grpc:
    host: 127.0.0.1
    port: 19084
