server:
  port: 18083

spring:
  application:
    name: match-service
  cloud:
    nacos:
      discovery:
        server-addr: 38.76.188.242:8848
        namespace: dev-hanlian
        username: nacos
        password: ${NACOS_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: health

grpc:
  server:
    port: 19083
