server:
  port: 18082

spring:
  application:
    name: im-service
  config:
    import: optional:nacos:im-service.yaml
  cloud:
    nacos:
      discovery:
        server-addr: 38.76.188.242:8848
        namespace: dev-hanlian
        username: nacos
        password: ${NACOS_PASSWORD}
      config:
        server-addr: 38.76.188.242:8848
        namespace: dev-hanlian
        username: nacos
        password: ${NACOS_PASSWORD}
        file-extension: yaml

management:
  endpoints:
    web:
      exposure:
        include: health

grpc:
  server:
    port: 19082
